xgboost:
  objective: 'reg:squarederror'
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 7
  min_child_weight: 1
  gamma: 0
  subsample: 1
  colsample_bytree: 1
  reg_lambda: 1
  reg_alpha: 0
  random_state: 42
